Static -> Instanced
GTNewHorizons/CodeChickenLib pull request #14
Opened 2023-12-20 19:54 UTC by mitchej123

* Now significantly more thread safe

2023-12-22 00:09 UTC, mitchej123 commented
To be tagged as 1.2.0

2023-12-22 01:20 UTC, Alexdoru submitted a review, later dismissed

2023-12-22 01:20 UTC, Alexdoru commented on src/main/java/codechicken/lib/asm/RedirectorTransformer.java
> +public class RedirectorTransformer implements IClassTransformer {
use the classpool parser thing to determine if the class needs transformation or not instead of making a ClassNode for every class

2023-12-22 13:56 UTC, Alexdoru commented on src/main/java/codechicken/lib/asm/RedirectorTransformer.java
>          if (basicClass == null) return null;
the null check here is redundant there is one ni the cstPoolParser

2023-12-23 10:13 UTC, Glease requested changes

2023-12-23 10:13 UTC, Glease commented on src/main/java/codechicken/lib/render/CCRenderState.java
> +        // public void prepareVertex();
comment seems unnecessary

2023-12-23 10:13 UTC, Glease commented on src/main/java/codechicken/lib/asm/RedirectorTransformer.java
> +                        mn.instructions.set(node, new MethodInsnNode(Opcodes.INVOKESTATIC, fNode.owner, fName, fDesc));
I'd prefer to insert a INVOKESTATIC instance() then SWAP before PUTSTATIC. This works too, but adds quite a bit of boilerplate method.

2023-12-23 10:13 UTC, Glease commented on src/main/java/codechicken/lib/gui/Canvas9Seg.java
> -    public void draw(int x, int y, int w, int h) {
Need an overload without state param to ensure compat

2023-12-23 10:13 UTC, Glease commented on src/main/java/codechicken/lib/render/CCRenderPipeline.java
> +    public CCRenderPipeline(CCRenderState renderState) {
need no arg overload

2023-12-23 10:13 UTC, Glease commented on src/main/java/codechicken/lib/render/CCRenderPipeline.java
> +        public PipelineBuilder(CCRenderState renderState) {
need no arg overload

though yeah I agree probably no one outside is using this constructor directly, but just in case

2023-12-24 17:57 UTC, Glease approved these changes
looks good

2023-12-24 18:07 UTC, merged